Add EditSetView and NoExerciseView
alex308248/GymBro pull request #19
Opened 2023-05-01 16:45 UTC by cheniwei

# Add EditSetView and NoExerciseView and Upgrade RoutineExerciseView
## EditSetView
- In the RoutineExerciseView, if some exercises have been added in the routine day, the user can see a "**+ Add Exercise**" button and a list of today's workout.
<img width="258" alt="Screenshot 2023-05-01 at 9 18 18 AM" src="https://user-images.githubusercontent.com/88813371/235487669-c79b81f1-0b8f-49fe-9f40-924086756bed.png">

- By clicking a exercise in the list, direct to the "**EditSetView**", and two dropdown wheel pickers will show. The user can choose to add a new set of weight and rep. 
- After choosing the weight and rep, click the title of the exercise, the dropdown pickers will close. (As the first fig)
<img width="266" alt="Screenshot 2023-05-01 at 9 18 28 AM" src="https://user-images.githubusercontent.com/88813371/235487707-13261fbe-ea61-4f78-ba05-a03cb5e7b72d.png">

- The default weight is set to be 120 lb, and the default rep is set to be 5 reps.
- The following figure is the example preview of an exercise in the list.
<img width="257" alt="Screenshot 2023-05-01 at 9 18 48 AM" src="https://user-images.githubusercontent.com/88813371/235488631-f0fd103d-7f8f-46aa-b014-20e17474ca8c.png">

## NoExerciseView
- If there is no exercise added in the list, the RoutineExerciseView will show a "**NoExerciseView**", which only has a "**+ Add Exercise**" button.
<img width="259" alt="Screenshot 2023-05-01 at 9 19 00 AM" src="https://user-images.githubusercontent.com/88813371/235488524-ae78ddc1-f0c7-4615-8e14-085540c203ab.png">

## RoutineExericseView
- Added a condition to determine whether there is any exercise in the list. If there is no exercise chosen or added to the list, the RoutineExerciseView will direct to the "**NoExerciseView**". Code shows as below.
- Comment out the following part for future use, since we haven't worked on ViewModel and Model.
```
if listViewModel.items.isEmpty {
    NoExerciseView()
        .transition(AnyTransition.opacity.animation(.easeIn))
} 
```
- If some exercises exist, show the "+ Add Exercise" button and the list of **EditSetView** for each exercise. Now assume there are some exercises in the list, thus the RoutineExerciseView shows as the first figure.

2023-05-01 18:41 UTC, YLee2121 commented on GymBro/Views/RoutineViews/RoutineExerciseView.swift
> +//            if listViewModel.items.isEmpty {
L41 (Line 41) ~ L44: 

Do these four lines of code need to be uncommented?

2023-05-01 18:51 UTC, YLee2121 commented on GymBro/Views/RoutineViews/RoutineExerciseView.swift
> +        NavigationView {
Remove this `NavigationView` due to the #16

2023-05-01 19:02 UTC, YLee2121 commented on GymBro/Views/RoutineViews/RoutineExerciseView.swift
Personal opinion: 

I think this file doesn't need an `if else` condition check for determining if there is added exercise or not.

L47 ~ L54 is similar to `NoExerciseView`, they both have this element.
``` swift
VStack {
                    List {
                        Button("+ Add Exercise", action: {
                            show sheet.toggle()
                        })
                        .sheet(isPresented: $showSheet, content: {
                            AddExerciseButton()
                        })

}
```

For the List structure, this is my idea in pseudo:

```swift

List {
    
    // add exercise button ( I simplified your button stack into only addExerciseButton for the convenience.)
    addExerciseButton

    // loop arount the exercise list if there is any exercise
    ForEach(exercised, id: \.self) {
        EditSetView(exercise: exercise)
    }
}

```

2023-05-01 19:08 UTC, YLee2121 commented on GymBro/Views/RoutineViews/EditSetView.swift
In `if !showPicker{}` and `if showPicker{}`, duplicate code and view (the exercise HStack) exist. Could you please try to refactor the script cleaner and avoid duplicate functionality?

2023-05-01 19:09 UTC, YLee2121 requested changes
Duplicate code in several files, please go to the file comment for more detail.

2023-05-02 17:42 UTC, cheniwei commented on GymBro/Views/RoutineViews/RoutineExerciseView.swift
I'll delete the NoExerciseView now and add `if else` condition for the ForEach loop.

2023-05-02 17:46 UTC, cheniwei commented on GymBro/Views/RoutineViews/EditSetView.swift
I think it's necessary since if I don't use this `showPicker` boolean variable, the view will look like this.
<img width="382" alt="Screenshot 2023-05-02 at 10 41 12 AM" src="https://user-images.githubusercontent.com/88813371/235743645-655d85eb-aaf2-4ab1-87bd-ab856dc23e03.png">

And if you look carefully at the trailing of `HStack { ... }`, the directions of `>` icon are different when closing and opening the dropdown picker.

2023-05-02 18:16 UTC, YLee2121 commented on GymBro/Views/RoutineViews/EditSetView.swift
Understand! I get a new idea, try to use the ternary operation `condition ? A : B` to refactor the view. 

reference pseudo code

```swift
var body: some View {
        VStack {
            HStack {
                Text(exercise)
                Image(systemzName: showPicker ? "chevron.right" : "chevron.down")
            }
            .onTapGesture {
                showPicker.toggle()
            }
            
            showPicker ? HStack { the whole picker HStack from L71 ~ L91 } : nil
            
        }
    }
```

2023-05-03 00:58 UTC, alex308248 commented
I got a question about the EditSetView. Will the customer see their previous sets in it? Since the code only shows how to add a new set to an exercise but each exercise might have several sets and customer should be able to see it. 

Something like the following from figma:
![image](https://user-images.githubusercontent.com/44662448/235815144-5aee63c3-3222-4eba-9f01-821dce5bfc35.png)

2023-05-25 16:54 UTC, merged