RoutineExerciseView First Pull Request
alex308248/GymBro pull request #7
Opened 2023-04-12 16:25 UTC by cheniwei

RoutineExerciseView:
1. Add new exercise by clicking "+ Add Exercise" to today's routine list. -> Link to AddExerciseButton view
2. Click "Finish" button to back to MainView.
4. Click "Edit" button to delete / move exercises in routine list.

AddExerciseButton:
1. Wheel picker for users to choose an existed exercise and click "Done" to add it to the routine list.
2. If there is no exercise the user wants, click "New" to add new exercise. -> Link to AddNewExercise

AddNewExercise:
1. TextField to type new exercise.
2. Click "SAVE" button to save the new exercise.

2023-04-12 18:02 UTC, alex308248 reviewed
It looks awesome!! 
The full process of uploading your code looks like the following: 
1. Commit your changes on your local machine and make sure it's working well
2. Pull the latest version of branch you're doing pr (eg. version1)
3. Merge version1 and your branch in your local machine and make sure there are no conflict.
4. Push your branch to github repo
5. Write your pull request and assign reviewers

An Example of the commands:
```
git checkout version1
git pull origin version1
git checkout cfork
git merge version1
git push
```

2023-04-12 20:44 UTC, YLee2121 commented on GymBro/Views/RoutineViews/AddExerciseButton.swift
> +    // MARK: PROPERTY
MARK guideline: 

Two blank lines above MARK and one blank line below MARK.

2023-04-12 20:45 UTC, YLee2121 commented on GymBro/Views/RoutineViews/AddExerciseButton.swift
> +                // Add a new exercise to the routine list
Comment guideline:

It needs a blank line above the comment.

2023-04-12 20:49 UTC, YLee2121 commented on GymBro/Views/RoutineViews/AddExerciseButton.swift
> +struct AddExerciseButton: View {
Documentation guideline:

If it's possible, please add some simple documentation. 
Check the "🎮Xcode Document" section in the GuideLines.md files.

2023-04-12 20:53 UTC, YLee2121 requested changes
In general, it's tidy and clean. 
Good job on the first PR.

Please check the comment about the documentation and try to solve them.

2023-04-15 00:38 UTC, alex308248 commented
This PR should be merging to `version1` but not main.

2023-04-18 23:54 UTC, YLee2121 approved these changes
Approved!

@alex308248 after you approve the PR, please press `Squash and merge`

2023-04-19 18:09 UTC, alex308248 approved these changes
Approved!

2023-04-19 22:59 UTC, merged